[package]
name = "exbf"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
flagset = "0.4.2"
syscalls = "0.5.0"
thiserror = "1.0.30"
